# Generated by Django 5.2.3 on 2025-07-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_offer_min_delivery_time_alter_offer_min_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_detail',
            new_name='offer_detail_id',
        ),
    ]
