# Generated by Django 5.2.3 on 2025-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_rename_offer_detail_order_offer_detail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_detail_id',
            new_name='offer_detail',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
