# Generated by Django 5.2.3 on 2025-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_rename_offer_detail_id_order_offer_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='offers/'),
        ),
    ]
