# Generated by Django 5.2.3 on 2025-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0006_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='offers/'),
        ),
    ]
